# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# From https://github.com/ZeelandFamily/zf-theme/blob/master/config.yml
# Change the below type value to 'html' if you want to develop using static HTML mockups
BROWSERSYNC:
  type: 'wordpress'
  host: 'transl-new.test'
  proxy: 'https://transl-new.test'
  # httpModule у меня не заработал с HTTPS ()
  # httpModule: 'http2'
  # https: true
  key: '/home/maxoud/www/LOCAL_DOMAINS_CERTS/transl-new.key'
  cert: '/home/maxoud/www/LOCAL_DOMAINS_CERTS/transl-new.crt'

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"
  - "android >= 4.4"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    # Search for used CSS classes in generated HTML files
    - "dist/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
